############################################################
#
# grpc-stream-tester Makefile
# Generated by amyznikov Mar 6, 2015
#
############################################################
SHELL = /bin/bash

CLIENT = client
SERVER = server

all : $(CLIENT) $(SERVER)

cross   =
sysroot =
DESTDIR =
prefix  = /usr/local
bindir  = $(prefix)/bin

PROTOS_PATH = ./
PROTOC = protoc
GRPC_CPP_PLUGIN = grpc_cpp_plugin
GRPC_CPP_PLUGIN_PATH ?= `which $(GRPC_CPP_PLUGIN)`


DEFINES  += -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DAMSCTL_VERSION=\"$(VERSION)\"
INCLUDES +=

CLIENT_SOURCES = client.cc
CLIENT_HEADERS =
CLIENT_MODULES = $(foreach s,$(CLIENT_SOURCES),$(addsuffix .o,$(basename $(s))))


SERVER_SOURCES = server.cc
SERVER_HEADERS =
SERVER_MODULES = $(foreach s,$(SERVER_SOURCES),$(addsuffix .o,$(basename $(s))))

PB_SOURCES = test.grpc.pb.cc test.pb.cc
PB_HEADERS = test.grpc.pb.h test.pb.h
PB_MODULES = $(foreach s,$(PB_SOURCES),$(addsuffix .o,$(basename $(s))))



#
# C preprocessor flags
CPPFLAGS = $(DEFINES) $(INCLUDES)

# C Compiler and flags
CC = $(cross)gcc
CFLAGS = -Wall -Wextra -O0 -g3

# C++ Compiler and flags
CXX = $(cross)g++ -std=c++11
CXXFLAGS = $(CFLAGS)


# Loader Flags And Libraries
LD = $(CXX)
LDFLAGS = $(CXXFLAGS)


LDLIBS += -L$(sysroot)/$(prefix)/lib -lgrpc++ -lprotobuf -lgrpc -lpthread -ldl -lstdc++ -lgpr


#########################################

$(CLIENT_SOURCES):$(PB_HEADERS)
$(SERVER_SOURCES):$(PB_HEADERS)

$(PB_HEADERS) $(PB_SOURCES): $(PROTOS_PATH)/test.proto Makefile
	$(PROTOC) -I $(PROTOS_PATH) --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=$(GRPC_CPP_PLUGIN_PATH) $<

%.pb.o: %.pb.cc
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -Wno-unused-parameter -c $< -o $@

$(PB_MODULES) $(MODULES) : $(PB_HEADERS) $(HEADERS) Makefile


$(CLIENT) : $(CLIENT_MODULES) $(PB_MODULES)
	$(LD) $(LDFLAGS) $(CLIENT_MODULES) $(PB_MODULES) $(LDLIBS) -o $@

$(SERVER) : $(SERVER_MODULES) $(PB_MODULES)
	$(LD) $(LDFLAGS) $(SERVER_MODULES) $(PB_MODULES) $(LDLIBS) -o $@

clean:
	$(RM) *.o

distclean: clean
	$(RM) $(CLIENT) $(SERVER) *.pb.cc *.pb.h

install: $(CLIENT) $(SERVER) $(DESTDIR)/$(bindir)
	cp $(CLIENT) $(SERVER) $(DESTDIR)/$(bindir)

uninstall:
	$(RM) $(DESTDIR)/$(bindir)/$(CLIENT) $(DESTDIR)/$(bindir)/$(SERVER)

$(DESTDIR)/$(bindir):
	mkdir -p $@
